apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  #namespace: istio-system
  name: additional-metrics-cb
spec:
  profile: default
  meshConfig:
    defaultConfig:
      proxyStatsMatcher:
        inclusionRegexps:
          - ".*circuit_breakers.*"
